### ISSUE TITLE
Add wiki pages to improve README 

### ISSUE THREAD

**Issue by Joneser** [zalando/gulp-check-unused-css#14]
Wiki pages should be added to augment the existing README

**Comment by prayerslayer** [comment]
Just my 2 cents: IIRC wiki pages are not versioned which means you can’t easily look up the docs for prior versions. Thus I’d put the docs in a separate folder in the repo instead, but do as you please.

**Comment by Joneser** [comment]
Thanks for giving me the headsup, I'll investigate before doing anything :)
