### ISSUE TITLE
Nothing is printed in the terminal

### ISSUE THREAD

**Issue by gsouquet** [zalando/gulp-check-unused-css#18]
Hi, 
First of all thank you for the plugin, it looks very good! So I wanted to try it on my project and nothing got printed on my terminal

I followed the different steps to install `gulp-check-unused-css` and here is my gulp file

``` js
var gulp = require('gulp');
var checkCSS    = require('gulp-check-unused-css');
gulp.task('css', function() {
    gulp.src(['/**/*.css', '/**/*.{jsp,tpl}'])
        .pipe(checkCSS());  
});
```

And here is what I get back in my terminal 

```
$> gulp css
[11:42:40] Using gulpfile ~/dev/project/gulpfile.js
[11:42:40] Starting 'css'...
[11:42:40] Finished 'css' after 13 ms
```

I first assumed that my `glob` was wrong and used [gulp-print](https://www.npmjs.com/package/gulp-print) to check that I was matching files and everything seems good!

I load the following version: 
- gulp : ^3.9.0
- gulp-check-unused-css : ^2.1.3

Am I doing something wrong here? I couldn't find relevant information in the read me to help me debug that.

Thanks

**Comment by savokiss** [comment]
I have the same problem. And finally find out that you must **return** your gulp pipe in your gulp task!

May be the new gulp caused this.

**Comment by LappleApple** [comment]
Hi @gsouquet and @savokiss, just noticing that you haven't gotten a response yet. Sorry about that. @Joneser, do you have any insights or suggestions for them?

**Comment by savokiss** [comment]
This works. Just add the `return`;
```
var gulp = require('gulp');
var checkCSS    = require('gulp-check-unused-css');
gulp.task('css', function() {
    return gulp.src(['/**/*.css', '/**/*.{jsp,tpl}'])
        .pipe(checkCSS());  
});
```

**Comment by Joneser** [comment]
Hi @savokiss , I'll resolve this issue later today and let you know when a new version is published to npm, thanks for this and my apologies for not getting back to you earlier!

**Comment by LappleApple** [comment]
Or: @savokiss, would you be willing to make a PR with the doc change, plus any recommended fixes?

**Comment by Joneser** [comment]
Added a small note to the readme, closing this issue :)
